#ifndef COREBRICK_VERSION_H
#define COREBRICK_VERSION_H

#define COREBRICK_VERSION_MAJOR 0
#define COREBRICK_VERSION_MINOR 4
#define COREBRICK_VERSION_PATCH 0
#define COREBRICK_VERSION_STRING "0.4.0"

#endif /* COREBRICK_VERSION_H */