#ifndef COREBRICK_VERSION_H
#define COREBRICK_VERSION_H

#define COREBRICK_VERSION_MAJOR 0
#define COREBRICK_VERSION_MINOR 3
#define COREBRICK_VERSION_PATCH 1
#define COREBRICK_VERSION_STRING "0.3.1"

#endif /* COREBRICK_VERSION_H */